### ISSUE TITLE
Not compatible with BepInEx 5.4.5

### ISSUE THREAD

**Issue by ElnRay** [MayouKurayami/KK_CyuVR#2]
The grip buttons would not work if this plugin is enabled and would work fine if this plugin is removed. BepInEx version is 5.4.5.

**Comment by MayouKurayami** [comment]
I can't reproduce this issue with HF Patch 3.7 and BepInEx 5.4.5.
What exactly was the symptom that led you to believe that the grip wasn't working?

Also, can you upload **output_log.txt** under _Koikatsu\KoikatuVR_Data_?

**Comment by ElnRay** [comment]
> I can't reproduce this issue with HF Patch 3.7 and BepInEx 5.4.5.
> What exactly was the symptom that led you to believe that the grip wasn't working?
> 
> Also, can you upload **output_log.txt** under _Koikatsu\KoikatuVR_Data_?

This problem happened when I only upgraded Bepinex from 5.4.3 to 5.4.5 and kept other plugins unchanged (in fact, after I upgraded Bepinex, not only this plugin cannot work. Many plugins were abnormal even in the non-VR game). Later I installed HF patch 3.7, and everything works fine. 

Sorry to disturb you.
